Repository veg-share/frontend-ui, pull requests merged in 2021-04, with the labels that each got.

#9 Install dependencies
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/examples/actions.spec.js
  cypress/integration/examples/aliasing.spec.js
  cypress/integration/examples/assertions.spec.js
  cypress/integration/examples/connectors.spec.js
  cypress/integration/examples/cookies.spec.js
  cypress/integration/examples/cypress_api.spec.js
  cypress/integration/examples/files.spec.js
  cypress/integration/examples/local_storage.spec.js
  cypress/integration/examples/location.spec.js
  cypress/integration/examples/misc.spec.js
  cypress/integration/examples/navigation.spec.js
  cypress/integration/examples/network_requests.spec.js
  cypress/integration/examples/querying.spec.js
  cypress/integration/examples/spies_stubs_clocks.spec.js
  cypress/integration/examples/traversal.spec.js
  cypress/integration/examples/utilities.spec.js
  cypress/integration/examples/viewport.spec.js
  cypress/integration/examples/waiting.spec.js
  cypress/integration/examples/window.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
Labels: Phase 1

#10 setup/ PWA structure
  public/index.html
  public/manifest.json
  pull_request_template.md
  src/App/App.css
  src/App/App.js
  src/App/App.test.js
  src/index.js
  src/reportWebVitals.js
  src/worker.js
  src/workerRegistration.js
Labels: Phase 1, documentation, set-up

#11 Component architecture
  src/App/App.js
  src/App/App.test.js
  src/Data/mockData.js
  src/Images/GitHub-Mark-64px.png
  src/Images/GitHub-Mark-Light-64px.png
  src/Images/LI-In-Bug.png
  src/components/Feed/Feed.css
  src/components/Feed/Feed.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/FormModal/FormModal.css
  src/components/FormModal/FormModal.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Post/Post.css
  src/components/Post/Post.js
  src/components/Search/Search.css
  src/components/Search/Search.js
  src/components/UserDetails/UserDetails.css
  src/components/UserDetails/UserDetails.js
  src/components/UserInteractions/UserInteractions.css
  src/components/UserInteractions/UserInteractions.js
  src/index.js
  src/views/HomeView/HomeView.css
  src/views/HomeView/HomeView.js
  src/views/ProfileView/ProfileView.css
  src/views/ProfileView/ProfileView.js
Labels: enhancement, set-up

#13 Add travis.yml file for CI and autodeployment configuration
  .travis.yml
  package.json
Labels: Developer, documentation, set-up

#15 Profile Display
  src/App/App.js
  src/Data/mockData.js
  src/Images/carrot.png
  src/Images/home.png
  src/Images/user.png
  src/components/Feed/Feed.css
  src/components/Feed/Feed.js
  src/components/Post/Post.css
  src/components/Post/Post.js
  src/components/UserDetails/UserDetails.css
  src/components/UserDetails/UserDetails.js
  src/components/UserInteractions/UserInteractions.css
  src/components/UserInteractions/UserInteractions.js
  src/views/HomeView/HomeView.css
  src/views/ProfileView/ProfileView.css
  src/views/ProfileView/ProfileView.js
Labels: Developer, User, enhancement

#18 Ci/update yml
  .travis.yml
  cypress/fixtures/mockData.json
  cypress/integration/examples/actions.spec.js
  cypress/integration/examples/aliasing.spec.js
  cypress/integration/examples/assertions.spec.js
  cypress/integration/examples/connectors.spec.js
  cypress/integration/examples/cookies.spec.js
  cypress/integration/examples/cypress_api.spec.js
  cypress/integration/examples/files.spec.js
  cypress/integration/examples/local_storage.spec.js
  cypress/integration/examples/location.spec.js
  cypress/integration/examples/misc.spec.js
  cypress/integration/examples/navigation.spec.js
  cypress/integration/examples/network_requests.spec.js
  cypress/integration/examples/querying.spec.js
  cypress/integration/examples/spies_stubs_clocks.spec.js
  cypress/integration/examples/traversal.spec.js
  cypress/integration/examples/utilities.spec.js
  cypress/integration/examples/viewport.spec.js
  cypress/integration/examples/waiting.spec.js
  cypress/integration/examples/window.spec.js
  cypress/integration/homeview_spec.js
Labels: Developer

#19 Update cypress tests to use beforeEach, pass starter tests
  cypress/integration/homeview_spec.js
Labels: Developer, bug, set-up

#20 Add main branch to deploy in .travis.yml
  .travis.yml
Labels: Developer, bug, set-up

#25 Update indentation for branch to deploy in .yml file
  .travis.yml
Labels: Developer, bug, documentation, set-up

#26 Ci/update yml indents
  .travis.yml
Labels: Developer, bug, documentation, set-up

#27 Service worker fix
  cypress/integration/homeview_spec.js
  src/index.js
  src/service-worker.js
  src/serviceWorkerRegistration.js
Labels: Developer, bug, enhancement

#28 Add html script to call service worker registration
  public/index.html
Labels: Developer, bug, documentation, set-up

#29 Feature/home view
  public/index.html
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Search/Search.css
  src/components/Search/Search.js
  src/components/UserInteractions/UserInteractions.css
  src/components/UserInteractions/UserInteractions.js
  src/views/HomeView/HomeView.css
  src/views/HomeView/HomeView.js
  src/views/ProfileView/ProfileView.css
Labels: HomeView, UserInteractions, enhancement

#30 Deployment transfer
  .github/workflows/ci.yml
  .travis.yml
  cypress.json
  cypress/integration/homeview_spec.js
  public/index.html
  src/components/Header/Header.js
Labels: bug, set-up, testing

#31 Mobile styling
  src/components/Feed/Feed.css
  src/components/Feed/Feed.js
  src/components/Footer/Footer.css
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/UserInteractions/UserInteractions.css
  src/views/HomeView/HomeView.css
Labels: Footer, Header, User, User ProfileView, enhancement, styling

#32 Feature/search functionality
  src/App/App.js
  src/Context/AppContext.js
  src/components/Feed/Feed.js
  src/components/Header/Header.js
  src/components/Search/Search.css
  src/components/Search/Search.js
  src/components/UserInteractions/UserInteractions.js
  src/views/HomeView/HomeView.js
  src/views/ProfileView/ProfileView.js
Labels: Search, bug

#33 Feature/home view and form modal updates
  public/favicon.ico
  public/index.html
  public/manifest.json
  src/App/App.css
  src/App/App.js
  src/Images/background-mint.jpg
  src/components/Feed/Feed.js
  src/components/Footer/Footer.js
  src/components/FormModal/FormModal.css
  src/components/FormModal/FormModal.js
  src/components/Header/Header.js
  src/components/Post/Post.js
  src/components/UserDetails/UserDetails.js
  src/components/UserInteractions/UserInteractions.css
  src/components/UserInteractions/UserInteractions.js
  src/views/HomeView/HomeView.css
  src/views/HomeView/HomeView.js
  src/views/ProfileView/ProfileView.css
  src/views/ProfileView/ProfileView.js
Labels: FormModal, HomeView, UserInteractions, enhancement

#34 Feature/styling updates
  public/index.html
  src/App/App.css
  src/Images/carrot2.png
  src/Images/home2.png
  src/components/Footer/Footer.css
  src/components/FormModal/FormModal.css
  src/components/FormModal/FormModal.js
  src/components/Header/Header.css
  src/components/Search/Search.css
  src/components/UserDetails/UserDetails.css
  src/components/UserDetails/UserDetails.js
  src/components/UserInteractions/UserInteractions.css
  src/views/HomeView/HomeView.css
  src/views/ProfileView/ProfileView.css
  src/views/ProfileView/ProfileView.js
Labels: accessibility, enhancement, styling

#35 Feature/apollo graphql requests
  package-lock.json
  package.json
  src/App/App.js
  src/Data/mockData.js
  src/components/Feed/Feed.js
  src/components/Post/Post.js
  src/components/Search/Search.css
  src/components/Search/Search.js
  src/index.js
  src/logo.svg
Labels: Feed, HomeView, Post, Search

#36 Fixes and testing
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/components/Footer/Footer.css
  src/components/FormModal/FormModal.css
  src/components/FormModal/FormModal.js
  src/components/UserInteractions/UserInteractions.css
  src/views/HomeView/HomeView.css
  src/views/ProfileView/ProfileView.css
Labels: styling

#37 Last minute fixes
  src/App/App.css
  src/App/App.js
  src/Images/loading.png
  src/components/Feed/Feed.js
  src/components/FormModal/FormModal.css
  src/components/FormModal/FormModal.js
  src/components/Post/Post.css
  src/components/Post/Post.js
  src/components/Search/Search.css
  src/components/UserInteractions/UserInteractions.js
  src/index.js
Labels: bug, enhancement
